default: &default
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5 #<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: users_trips_dev

test:
  <<: *default
  database: users_trips_test

production:
  <<: *default
  database: users_trips_production
